### ISSUE TITLE
Syntax highlighting for strings containing a "#" is incorrect

### ISSUE THREAD

**Issue by marktani** [prismagraphql/vscode-graphql#16]
![image](https://user-images.githubusercontent.com/1780597/41405292-bd8a553a-6fc9-11e8-9d09-5669780fe3b2.png)

`@default(value: "#123456")`, `#123456` should be printed as a normal string, not as a comment.

Also happens when `#` is in the middle of a string:

![image](https://user-images.githubusercontent.com/1780597/41405356-e3b0ca96-6fc9-11e8-9ecb-992c9de92f2d.png)

**Comment by divyenduz** [comment]
Released in `0.0.9` 🎉
