### ISSUE TITLE
Syntax highlighting for docstring comments is incorrect

### ISSUE THREAD

**Issue by AndrewIngram** [prismagraphql/vscode-graphql#19]
It's valid syntax for docstring comments to have no line breaks, but the syntax highlighting fails on them, causing everything below to be treated as a comment.

![image](https://user-images.githubusercontent.com/35227/41466770-900599b2-709b-11e8-8bae-f43dc3edf85a.png)

![image](https://user-images.githubusercontent.com/35227/41466818-c9b5c7a4-709b-11e8-813a-4cc3f9868e83.png)

**Comment by marktani** [comment]
> The syntax highlighter does not handle argument comments correctly. [More context](https://github.com/graphql/graphql-js/issues/1285).
