### ISSUE TITLE
Syntax highlighting breaks on some point.

### ISSUE THREAD

**Issue by borisowsky** [prismagraphql/vscode-graphql#22]
![image](https://user-images.githubusercontent.com/14042959/41476027-958ff5ba-70c0-11e8-8df9-6d84ca247700.png)

OS: MacOS High Sierra 10.13.4
VSCode: 1.24.1

This is generated schema by Prisma service, so there is something went wrong on syntax highlighting.

**Comment by marktani** [comment]
Thanks for the report! The syntax highlighter does not handle argument comments correctly. [More context](https://github.com/graphql/graphql-js/issues/1285).

**Comment by marktani** [comment]
Closing as duplicate of #19.
