### ISSUE TITLE
Clicking on status bar entry returns useless notification

### ISSUE THREAD

**Issue by peterschussheim** [prismagraphql/vscode-graphql#26]
<img width="391" alt="google chrome026" src="https://user-images.githubusercontent.com/3654683/41604876-3d363442-73ae-11e8-9a56-80350086e987.png">

**Comment by divyenduz** [comment]
Thanks for the report. This will be fixed in `0.0.10` once https://github.com/prismagraphql/vscode-graphql/pull/39 is merged.

**Comment by divyenduz** [comment]
Released in `0.0.10` 🎉
