### ISSUE TITLE
Tail extension and language server logs to vscode output console

### ISSUE THREAD

**Issue by peterschussheim** [prismagraphql/vscode-graphql#28]
It is very useful for extensions and language servers to send logs (info and errors) to vscode's output console.  Below is an example what `tsserver` task output looks like.

![tsserver](https://user-images.githubusercontent.com/3654683/41606415-a043cd30-73b1-11e8-9f83-9a6e0b7558d8.png)

**Comment by divyenduz** [comment]
Added instructions to log both graphql and TS language service. Please re-open if you think that this is not enough. Thanks.

**Comment by peterschussheim** [comment]
@divyenduz Those instructions seem to be targeted towards developing this extension, correct?  I was thinking the extension logs should be sent to output.  See a below screenshot of how [GraphQL for VSCode](https://github.com/kumarharsh/graphql-for-vscode.git) does this:

<img width="1275" alt="code - insiders007" src="https://user-images.githubusercontent.com/3654683/41855537-e0294f2a-7860-11e8-989a-1e65013ecb34.png">

**Comment by peterschussheim** [comment]
OK, my bad, found it!  Thanks 👍
