### ISSUE TITLE
Getting errors on local schema file with custom built directives

### ISSUE THREAD

**Issue by andres-gr** [prismagraphql/vscode-graphql#31]
I have a custom directive declared in my local schema file, and it is throwing validation errors when used in this file.

`[GraphQL: Validation] Unknown directive "withAuth"`

![screen shot 2018-06-19 at 11 46 36 am](https://user-images.githubusercontent.com/26035230/41611926-f9996070-73b6-11e8-9688-2dcc3a0bc2c4.png)

Maybe it's a bug?

Maybe we can have an option in the settings for the extension to declare our own directives or maybe to ignore such errors.

**Comment by divyenduz** [comment]
@andres-gr : Thanks for reporting the issue, I think that extension is not activated for you for some reason as the directive syntax highlighting is not working. 

I was not able to reproduce this and [it works](http://recordit.co/fyFGHYIjQE) for me.

Do you see a plug symbol with graphql in your status bar? This signifies that extension is in play. 
<img width="78" alt="screen shot 2018-06-25 at 2 39 38 pm" src="https://user-images.githubusercontent.com/746482/41850674-aeab0f2c-7885-11e8-93eb-9232acb6e563.png">

If yes, can you please share a sample repository where this behavior can be observed. 

Thanks!

**Comment by andres-gr** [comment]
@divyenduz thanks for the feedback, I guess I did have something wrong in my `.graphqlconfig` file as it is now working after doing some changes to that file.

I guess you can close this issue.

**Comment by johannpinson** [comment]
Hello @divyenduz 

I got the same bug, even if the plugin is running well
![capture d ecran 2018-07-18 a 15 53 34](https://user-images.githubusercontent.com/2202989/42889473-d1e7e776-8aaa-11e8-95d5-b886a5735c2b.png)

Is the plugin works only with Schema directives (and not directiveResolvers ?)
My actual code follow this example: https://github.com/LawJolla/prisma-auth0-example

Thanks,

**Comment by steebchen** [comment]
I have the same issue. The output tab in VS Code showed some weird errors, and I realized it's because of using a project name with a hyphen:

```
projects:
  my-project:
    [...]
```
