### ISSUE TITLE
Do I need .graphqlconfig.yml to use the extension?

### ISSUE THREAD

**Issue by christiannwamba** [prismagraphql/vscode-graphql#32]
Since this extension works with `gql`, do I need `.graphqlconfig` to use it? It keeps popping this error whenever I launch a GraphQL project:

<img width="565" alt="screen shot 2018-06-19 at 8 57 04 pm" src="https://user-images.githubusercontent.com/8108337/41621141-be3169fe-7403-11e8-83b0-2eb77da9dd5c.png">

**Comment by divyenduz** [comment]
The extension kicks in when graphql config file is present. However, the extension will work with `.graphql` files. 

We should make the extension silent about existence of graphql config file. 

Closing this one as it is covered in https://github.com/prismagraphql/vscode-graphql/issues/7
