### ISSUE TITLE
Support graphql imports.

### ISSUE THREAD

**Issue by corycook** [prismagraphql/vscode-graphql#34]
When you are using the `graphql-tag/loader` plugin for webpack you can use graphql imports to pull fragments from other files.

```graphql
#import "./MyFragment.graphql"

query test {
  item {
     ...MyFragment
  }
}
```

Hovering over the fragment logs the following to the GraphQL Language Server log:
"Definition not found for GraphQL fragment MyFragment"

**Comment by divyenduz** [comment]
@corycook Thanks for reporting this issue. Currently, we support this by defining the dependencies in `includes` field of graphql config. Please see the [usage section](https://github.com/prismagraphql/vscode-graphql#usage).

**Comment by corycook** [comment]
Okay, I thought that was for graphql schema definition files I didn't think it would be for fragment definitions as well.

How does this handle multiple fragments with the same name? I don't have any, just curious.

**Comment by corycook** [comment]
It looks like this functionality has since been added this can probably be closed.
