### ISSUE TITLE
Logo for extension

### ISSUE THREAD

**Issue by sorenbs** [prismagraphql/vscode-graphql#5]
@kuldar - we need a logo :-)

![image](https://user-images.githubusercontent.com/281337/41218629-03eb80dc-6d5c-11e8-9955-c09eccb9383e.png)

**Comment by everdrone** [comment]
@kuldar this looks amazing
made it my welcome screen imprint

![welcome](https://user-images.githubusercontent.com/22671061/41466398-61f198f8-70a2-11e8-96d0-945991647743.png)

**Comment by orta** [comment]
This is great design work - kudos

**Comment by divyenduz** [comment]
Thanks @kuldar for the awesome icon.
