### ISSUE TITLE
Make it possible to have .env file in same directory of prisma.yml when in a sub directory

### ISSUE THREAD

**Issue by timsuchanek** [prismagraphql/vscode-graphql#9]
Lets say I have this folder structure:

```
.
├── .graphqlconfig.yml
└── app
    ├── .env
    └── prisma.yml
```

Right now the extension doesn't evaluate the .env file.
This is an issue in `prisma-yml`

**Comment by divyenduz** [comment]
Tracking here: https://github.com/prismagraphql/prisma/issues/1701
